In [1]:
#!pip install transformers tensorflow

In [2]:
#pip install transformers torch

In [3]:
#pip install torch transformers datasets

In [16]:
#pip install --upgrade torch transformers datasets

In [3]:
import torch

In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from transformers import Trainer, TrainingArguments

In [5]:
df = pd.read_csv("NLP with disaster tweets.csv")

In [6]:
texts = list(df['text'].values)
labels = list(df['target'].values)

In [7]:
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

encodings = tokenizer(texts, truncation=True, padding=True, max_length=64)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

# Create PyTorch Dataset

In [8]:
class DisasterDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_texts, test_texts, train_labels, test_labels = train_test_split(texts, labels, test_size=0.2)

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=64)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=64)

train_dataset = DisasterDataset(train_encodings, train_labels)
test_dataset = DisasterDataset(test_encodings, test_labels)

# Load Pretrained Model

In [9]:
model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [10]:
pip install transformers[torch]

Requirement already satisfied: transformers[torch] in c:\users\mehak\anaconda3\lib\site-packages (5.13.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (1.23.0)
Requirement already satisfied: numpy>=1.17 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (2026.7.10)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (0.20.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\users\mehak\anaconda3\lib\site-packages (from transformers[torch]) (2.13.0)
Collecting accelerate>=1.1.0 (from transformers[torch])
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\mehak\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\mehak\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\mehak\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\mehak\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\mehak\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\mehak\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: colorama in c:\users\mehak\anaconda3\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: anyio in c:\users\mehak\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.10.0)
Requirement already satisfied: certifi in c:\users\mehak\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\mehak\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\mehak\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\mehak\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: psutil in c:\users\mehak\anaconda3\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (7.0.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\mehak\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\mehak\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\mehak\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.5)
Requirement already satisfied: jinja2 in c:\users\mehak\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\mehak\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\mehak\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mehak\anaconda3\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\mehak\anaconda3\lib\site-packages (from typer->transformers[torch]) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\mehak\anaconda3\lib\site-packages (from typer->transformers[torch]) (14.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\mehak\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers[torch]) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\mehak\anaconda3\lib\site-packages (from rich>=10.11.0->typer->transformers[torch]) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\mehak\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers[torch]) (0.1.2)
Downloading accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0
Note: you may need to restart the kernel to use updated packages.

# Define Training Arguments

In [10]:
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    save_strategy="epoch",
    logging_dir='./logs',
    logging_steps=10,
)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

# Initialize Trainer

In [11]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

# Train & Evaluate

In [12]:
trainer.train()
trainer.evaluate()

C:\Users\Mehak\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Mehak\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Mehak\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

C:\Users\Mehak\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

{'eval_loss': 0.5153114199638367}

# Make Predictions

In [20]:
sample_text = ["I love spending my weekends watching movies with friends!"]
inputs = tokenizer(sample_text, return_tensors="pt", truncation=True, padding=True, max_length=64)
outputs = model(**inputs)
pred = torch.argmax(outputs.logits, dim=1).item()

print("Disaster Tweet" if pred == 1 else "Not Disaster Tweet")

Not Disaster Tweet

In [14]:
results = trainer.evaluate()
print(results)

{'eval_loss': 0.5153114199638367}

In [19]:
from sklearn.metrics import accuracy_score

# Get predictions
predictions = trainer.predict(test_dataset)
y_pred = np.argmax(predictions.predictions, axis=1)

# Accuracy
acc = accuracy_score(test_labels, y_pred)
print(f"Test Accuracy: {acc*100:.2f}%")

Test Accuracy: 83.91%